### ISSUE TITLE
How to run the training model

### ISSUE THREAD

**Issue by q01010101** [peng-lab/HistoBistro#10]
Hi! As a beginner, After I readed the readme.txt, I run the sentence:
  "python train_k-fold.py --name <name> --data_config <path/to/data_config.yaml> --config <path/to/config.yaml>"(of course I wrote down my own path)
  in Anaconda prompt, but it gave me a error which showed:
  "Incorrect file name, directory name, or volume label syntax: 'D:\\HistoBistro-main\\HistoBistro-main\\models\\try1_<Transformer\\TransMIL\\AttentionMIL\\...>_<cohort_name1>-<cohort_name2>_<normalizatio_used>_<target>'"
  It seemslike indicate that the error is occurring in the <name> part, and some part is vacant.
  So could you please tell me how to fix the sentence and make it run successfully? I don't have the luxury of being able to run all the code anymore, but I'd still like to be able to implement at least some of it...THX!

**Comment by ValentinKoch** [comment]
Hi, sorry for the delayed response! Did you solve your problem already? It seems like the syntax is not correct of the path you are giving: im not entirely sure but you might need to use double dashes? e.g. D:\\HistoBistro-main\\HistoBistro of forward dashes D:/HistoBistro-main/HistoBistro... ? if in doubt with simple syntax errors ChatGPT can be of great help :) 

Best
Valentin
