### ISSUE TITLE
Questions about the size of tiles used to extract features

### ISSUE THREAD

**Issue by Gaodelike** [peng-lab/HistoBistro#11]
Hi, thank you for making such a great framework!

I have a question about CTransPath, I checked the literature on this method and found that the image input size of the model provided by the author is 224*224，

In your literature, it is mentioned that 512*512, I would like to ask what method was used to modify the size of the image? I haven't figured out how it works yet, I hope to get your advice, thank you!

**Comment by ValentinKoch** [comment]
Dear Gaodelike,

sorry for the delayed response and thanks for your interest! We resize the image to the size the feature extractor was originally trained on, so in this case the image is downscaled to 224x224 👍 You can look into the feature extraction branch of this repository, the resizing gets done inside the transformations, the rescaling sizes are found in models/model.py inside get_transforms().
Best
Valentin
