### ISSUE TITLE
Inquiry of code for feature extractor and data preprocessing

### ISSUE THREAD

**Issue by OMIC-coding** [peng-lab/HistoBistro#12]
I noticed that you summarized 'Our model consists of a transformer-based feature extractor that was pretrained on histopathology images and a transformer-based aggregation module' in the paper. Could you please provide the code for data pre-processing and transformer-based feature extractor? I will really appreciate your generous help.

**Comment by ValentinKoch** [comment]
Hi, the code for preprocessing is in the feature_extractor branch of this repository! Including a guide how to use the feature extractor used in the paper (CTransPath). I will close this issue but feel free to reach out if you have more questions :)
