### ISSUE TITLE
ctranspath running error

### ISSUE THREAD

**Issue by rushin682** [peng-lab/HistoBistro#6]
RuntimeError: Error(s) in loading state_dict for SwinTransformer:
	Missing key(s) in state_dict: "patch_embed.proj.weight", "patch_embed.proj.bias". 
	Unexpected key(s) in state_dict: "patch_embed.proj.0.weight", "patch_embed.proj.1.weight", "patch_embed.proj.1.bias", "patch_embed.proj.1.running_mean", "patch_embed.proj.1.running_var", "patch_embed.proj.1.num_batches_tracked", "patch_embed.proj.3.weight", "patch_embed.proj.4.weight", "patch_embed.proj.4.bias", "patch_embed.proj.4.running_mean", "patch_embed.proj.4.running_var", "patch_embed.proj.4.num_batches_tracked", "patch_embed.proj.6.weight", "patch_embed.proj.6.bias". 

Need to fix

**Comment by ValentinKoch** [comment]
Hi Rushin,
i updated the requirements to install the correct timm library that is attached in the repository. You can install it manually by running 'pip install timm-0.5.4.tar'. If issues persists please let me know :)
